### ISSUE TITLE
Conditional execution of different rules depending on changes of one file

### ISSUE THREAD

**Issue by maetra** [cereda/arara#86] opened 2016-12-21 22:39 UTC
Consider the following example in arara 4.0:

% arara: pdflatex: {files: [example.tex]} if changed(toFile('example.tex'))
% arara: biber
% arara: pdflatex: {files: [example.tex]} if found(toFile('example.log'), "Package biblatex Warning: Please")
% arara: indent: {files: [example.tex]} if changed(toFile('example.tex'))

In this case, the indent rule is not executed as the hash codes in arara.xml are already rewritten. If for each rule separate values were stored, the indent rule would be executed. Alternatively, if the if condition were applied to several rules, one would be able to solve this issue more elegantly.

**Comment by cereda** [comment] 2016-12-22 11:36
Hello!

You are absolutely right: on each invocation of `changed(...)`, the external file `arara.xml` is updated. In subsequent invocations, the new values are used. It was an implementation decision, so this particular behaviour is by design.

However, I can see how one could not benefit from a compilation chain when in need to run multiple `changed(...)` verifications, as your example clearly demonstrates this scenario. I have an idea to solve this issue with a small change to my code. Here's my idea:

There's a special singleton object in the rule scope named *session*. It is meant to allow rules to talk to each other. It persists values during the entire compilation chain. So far, this object is only available in the rule scope, not in the directive one. It could be only a matter of including this session object in both scopes instead of just one. Your example would be rewritten as follows:

```tex
% arara: pdflatex: {files: [example.tex]}
% arara: --> if getSession.insert("changed", changed(toFile('example.tex'))); 
% arara: --> getSession.obtain("changed")
% arara: biber
% arara: pdflatex: {files: [example.tex]}
% arara: --> if found(toFile('example.log'), "Package biblatex Warning: Please")
% arara: indent: {files: [example.tex]} if getSession.obtain("changed")
```

Not sure if this would be the best approach, but it's doable...

**Comment by TheTeXnician** [comment] 2020-09-28 07:44
We have re-evaluated matters for the upcoming version 6 and we still think that using the session is the way to persist information. That means we have not found anything superior to @cereda's solution which is applicable to a wider use. For that reason, we will close this issue. If you feel that there is a superior solution, please let us know, we are open to discuss suggestions.

**Closed by TheTeXnician** 2020-09-28 07:44 UTC
