### ISSUE TITLE
Feature request: Ability to set arara configuration file directory from .tex file header

### ISSUE THREAD

**Issue by itskando** [cereda/arara#140] opened 2020-09-20 16:48 UTC
From [here](https://tex.stackexchange.com/questions/563392/arara-subdirectories-and-arara-preamble-araracommandfilename-texfilen?noredirect=1#comment1420106_563392), it was suggested to bring this to your attention : j

If I have a series of .tex files which are able to be to run standalone via `\usepackage{standalone}` and also as a subfile from a parent file via `\input{<subfileName.tex>}`, I similarly place `arara` headers in every `standalone` subfile. For the former, running the `.tex` file standalone, I drop an `arara` header into every standalone file, which means remembering to update all of them should the `arara` text change.

It would be nice, however, if I could simply place in the `arara` header a redirect (via a relative path) to a directory containing a master `arara` configuration file.

**Really rough psuedoexample**:

```
% arara: upticks="../../.."
% arara: config { path: [upticks '/Subfiles/0-Preamble/araraconfig.yaml']
```

**Comment by TheTeXnician** [comment] 2020-09-21 08:57
This does seem a bit strange. Unless, you really need configuration options that cannot be passed via command-line, why don't you use a custom rule and put it into one of the paths searched by arara? To understand your request, it would be nice to have an example of your configuration and used directives to see what would be needed what's not covered by custom rules.

**Comment by cereda** [comment] 2020-09-22 11:37
As of the current release, directives are typically stateless (modulo `Session` through conditionals), so it would not be possible to propagate data from one to another without a complete redesign of the current implementation. They are, by design, mere rule instances sometimes bound by a logical expression which will determine whether and how this instance should be tackled. Anything which is not a rule instance will trigger an error.

For the record, we are indeed discussing directive argument expansion for future releases as a means to make the rule instance more dynamic and fluid. It is worth mentioning, however, that expansion can already happen at rule scope (when applicable). The next major release has now a modular approach which will hopefully ease development.

I wholeheartedly agree with @TheTeXnician that a custom rule would be the best option, but we need to learn a bit more about your work flow. It is possible to search for files and even keep track of their modification statuses. The idea is to move the complexity from the directive to the rule scope, in which could be way more powerful and efficient.

It is also worth mentioning that we are working on a new _project_  feature for the next major version, which is surprisingly close to your work flow (of course, we need more info on that). This feature aims at easing the specification of a proper project, so the document structure is not seen just as a set of independent TeX files, but as a coherent model. We are still in alpha, but results look promising (gosh, I sound like my own academic papers). :wink:

**Comment by TheTeXnician** [comment] 2020-09-28 07:59
@itskando As we are currently actively revising directives and rules for version 6, we would appreciate feedback and details. Some points we need clarification on:

- How are you actually using preambles? Are there any special features of preambles that you need?  
  (background: we intend to remove preambles in the long run in favor of project configuration files and need to understand user's needs)
- In your directory structure, which files do you call arara on?
- Do you use project-wide configuration or user configuration files?

**Comment by TheTeXnician** [comment] 2020-11-06 20:43
I'm closing this for now because we are unable to understand the feature request and no details were supplied. We will happily reopen if you add some more details so that we are able to evaluate the feature request.

**Closed by TheTeXnician** 2020-11-06 20:43 UTC

**Comment by itskando** [comment] 2020-11-06 20:45
Sorry - I've been side tracked on other projects. Probably won't return to
tex related projects for a few weeks

**Comment by TheTeXnician** [comment] 2020-11-06 20:47
> Sorry - I've been side tracked on other projects. Probably won't return to tex related projects for a few weeks

Don't worry, when you've got the time simply add some details here and ping Paulo or me and we will discuss it with you then :slightly_smiling_face:
